### ISSUE TITLE
Slick Slider kweshun

### ISSUE THREAD

**Issue by nominalaeon** [kenwheeler/ama#22]
Slick Slider is crazy popular and prolific, and I realize you're more than that one component, but I've always wondered what that's like, to have something gain popularity and just take off on its own like that.

I guess my questions are: how proud of Slick are you? Knowing what you know now, would you still have created it? What's your favorite and least favorite aspects of that specific tool?

**Comment by kenwheeler** [comment]
I released Slick at a time when I got really happy over 30 stars. I knew it was good, because it solved problems at work for me, and colleagues seemed to enjoy it. When It started getting really popular, I was so happy that I would take any request, field every issue, almost in real time. Super quick bug turnaround and feature addition.

Im very proud of Slick. Its used on so many sites that it still blows my mind.

However, with the good, comes the bad. Shitposters, haters, entitled crazy github posters. In retrospect, I would have been more selective over options and features to keep the API slimmer.  I wish I could give it more love these days but:

- Im busy as fuck being a dad and with my job
- I flat out havent used it in years. I build things differently now.
- im out of the loop for the kinds of things people want these days

Issues and PRs became unmanageable, and the more that piled up, the less I felt like picking away at the issues would even help. 

That said, I still do intend to rewrite it for modern use and in a way that some hotly requested features can be implemented. I just need to find the time! I promise, I will 2.0 it.

**Comment by nominalaeon** [comment]
1.6 (and 1.5 really) was such a modernization, I'm not sure it even needs 2.0'ing. I imagine it will be a long time before any of that code is invalid, but that's cool to hear you have embers of enthusiasm left.

One more question and this comes from personal experience, but remember how awesome hair was? So awesome, right?

**Comment by kenwheeler** [comment]
I have a full head of hair. I just remove it because I dont like it. For 15 years now. Ive thought about growing it out recently, but the in between period i look like a corgi or something
