### ISSUE TITLE
What is your greatest insecurity? 

### ISSUE THREAD

**Issue by jazlalli** [kenwheeler/ama#8]

**Comment by kenwheeler** [comment]
That im not actually smart enough. I didnt go to college and everyone else is very smart. Feels like someday everyone is going to figure out that im backfilling technical proficiecy with social ability. That and my current weight. Ive been traditionally handsome, and this somewhat recent 30-40lbs is a bummer.

**Comment by kenwheeler** [comment]
Actually, im pretty sure the cats out of the bag on that one lol

**Comment by jazlalli** [comment]
I feel ya bro

**Comment by kenwheeler** [comment]
[hugs]

**Comment by modernkd** [comment]
For what it's worth, I love the badass stuff you build and the different take you have on the same shit we all use. Social ability is hard to learn, and college doesn't really mean much in the grand scheme of things. You inspire a lot of people to be okay with doing something because it sounds cool and not because it's necessary.

**Comment by kenwheeler** [comment]
[doublehugs]

**Comment by joelkinzel** [comment]
[Imposter Syndrome](https://en.wikipedia.org/wiki/Impostor_syndrome) is a huge thing that virtually everyone has experienced and virtually no one knows or talks about. I have it constantly. Here is a good FEHH had a [great episode](https://soundcloud.com/front-end-happy-hour/episode-032-imposter-syndrome-these-are-not-the-drinks-youre-looking-for) on it recently.
